#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
# Book settings
title                       : The Turing Way  # The title of the book. Will be placed in the left navbar.
author                      : The Turing Way Community  # The author of the book
copyright                   : "2020-2021"  # Copyright year to be placed in the footer
logo                        : "./figures/logo/logo.jpg"  # A path to the book logo
exclude_patterns            : ["LICENSE.md"]  # Patterns to skip when building the book. Can be glob-style (for example "*skip.ipynb")

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : ["LICENSE.md"]  # A list of patterns to *skip* in execution (for example a notebook that takes a really long time)

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "./figures/logo/favicon-32x32.png"  # A path to a favicon image
  navbar_number_sections    : False  # Add a number to each section in your left navbar
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  extra_navbar              : Visit our <a href="https://github.com/alan-turing-institute/the-turing-way">GitHub Repository</a>
    <div>This book is powered by <a href="https://jupyterbook.org">Jupyter Book</a></div>
  comments:
    hypothesis: true

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : "classic"  # The interface interactive links will activate ["classic", "jupyterlab"]
  thebelab                  : false  # Add a thebelab button to pages (requires the repository to run on Binder)

repository:
  path_to_book              : "book/website"  # A path to your book's folder, relative to the repository root.
  branch                    : main

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions          :  # A list of extra extensions to load by Sphinx.
  config                    :  # key-value pairs to directly over-ride the Sphinx configuration
    language                : en

bibtex_bibfiles:
    - _bibliography/references.bib
