project_id: '1'
api_token: 919b778d8f5f3892b1eaea1458b0b2dc60d29219be5b66f2f4b5b1621720e013e7be0acaa6ba654f
base_url: 'https://turingway.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /book/website/
    translation: /book/translation/%three_letters_code%/%original_path%/%original_file_name%
